import { type ComponentType } from "react";

function toSvgComponent(moduleValue: any): ComponentType<any> {
  return (moduleValue?.default ?? moduleValue) as ComponentType<any>;
}

export const QUESTION_VISUALS: Record<string, ComponentType<any>> = {
  "nouns-dog": toSvgComponent(require("../../assets/questions/nouns-dog.svg")),
  "nouns-water": toSvgComponent(require("../../assets/questions/nouns-water.svg")),
  "nouns-child": toSvgComponent(require("../../assets/questions/nouns-child.svg")),
  "nouns-sun": toSvgComponent(require("../../assets/questions/nouns-sun.svg")),
  "nouns-house": toSvgComponent(require("../../assets/questions/nouns-house.svg")),
  "nouns-road": toSvgComponent(require("../../assets/questions/nouns-road.svg")),
  "nouns-food": toSvgComponent(require("../../assets/questions/nouns-food.svg")),
  "nouns-book": toSvgComponent(require("../../assets/questions/nouns-book.svg")),
  "nouns-friend": toSvgComponent(require("../../assets/questions/nouns-friend.svg")),
  "nouns-money": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "pronouns-i": toSvgComponent(require("../../assets/questions/pronouns-i.svg")),
  "pronouns-you": toSvgComponent(require("../../assets/questions/pronouns-you.svg")),
  "pronouns-he": toSvgComponent(require("../../assets/questions/pronouns-he.svg")),
  "pronouns-she": toSvgComponent(require("../../assets/questions/pronouns-she.svg")),
  "pronouns-we": toSvgComponent(require("../../assets/questions/pronouns-we.svg")),
  "pronouns-they": toSvgComponent(require("../../assets/questions/pronouns-they.svg")),
  "pronouns-me": toSvgComponent(require("../../assets/questions/pronouns-me.svg")),
  "pronouns-us": toSvgComponent(require("../../assets/questions/pronouns-us.svg")),
  "pronouns-them": toSvgComponent(require("../../assets/questions/pronouns-them.svg")),
  "pronouns-my": toSvgComponent(require("../../assets/questions/pronouns-my.svg")),
  "verbs-eat": toSvgComponent(require("../../assets/questions/verbs-eat.svg")),
  "verbs-go": toSvgComponent(require("../../assets/questions/verbs-go.svg")),
  "verbs-come": toSvgComponent(require("../../assets/questions/verbs-come.svg")),
  "verbs-see": toSvgComponent(require("../../assets/questions/verbs-see.svg")),
  "verbs-speak": toSvgComponent(require("../../assets/questions/verbs-speak.svg")),
  "verbs-sleep": toSvgComponent(require("../../assets/questions/verbs-sleep.svg")),
  "verbs-read": toSvgComponent(require("../../assets/questions/verbs-read.svg")),
  "verbs-write": toSvgComponent(require("../../assets/questions/verbs-write.svg")),
  "verbs-work": toSvgComponent(require("../../assets/questions/verbs-work.svg")),
  "verbs-play": toSvgComponent(require("../../assets/questions/verbs-play.svg")),
  "custom-everyday-verbs-a-na-m-aga-oru-kwa-ututu": toSvgComponent(require("../../assets/questions/custom-everyday-verbs-a-na-m-aga-oru-kwa-ututu.svg")),
  "custom-everyday-verbs-anyi-na-ehi-ura-n-oge-izu": toSvgComponent(require("../../assets/questions/custom-everyday-verbs-anyi-na-ehi-ura-n-oge-izu.svg")),
  "custom-everyday-verbs-ha-na-eri-osikapa-maka-nri-mgbede": toSvgComponent(require("../../assets/questions/custom-everyday-verbs-ha-na-eri-osikapa-maka-nri-mgbede.svg")),
  "custom-everyday-verbs-i-na-eje-ije-ngwa-ngwa-nke-ukwuu": toSvgComponent(require("../../assets/questions/custom-everyday-verbs-i-na-eje-ije-ngwa-ngwa-nke-ukwuu.svg")),
  "custom-everyday-verbs-o-biarutere-n-ulo-mgbe-e-mesiri": toSvgComponent(require("../../assets/questions/custom-everyday-verbs-o-biarutere-n-ulo-mgbe-e-mesiri.svg")),
  "custom-everyday-verbs-o-na-anu-mmiri-mgbe-egwuregwu-bol-gachara": toSvgComponent(require("../../assets/questions/custom-everyday-verbs-o-na-anu-mmiri-mgbe-egwuregwu-bol-gachara.svg")),
  "custom-everyday-verbs-umuaka-na-agba-oso": toSvgComponent(require("../../assets/questions/custom-everyday-verbs-umuaka-na-agba-oso.svg")),
  "custom-greetings-a-bu-m-si": toSvgComponent(require("../../assets/questions/custom-greetings-a-bu-m-si.svg")),
  "custom-greetings-achoro-m-mmiri": toSvgComponent(require("../../assets/questions/custom-greetings-achoro-m-mmiri.svg")),
  "custom-greetings-aguu-na-agu-m": toSvgComponent(require("../../assets/questions/custom-greetings-aguu-na-agu-m.svg")),
  "custom-greetings-aha-m-bu-udoka": toSvgComponent(require("../../assets/questions/custom-greetings-aha-m-bu-udoka.svg")),
  "custom-greetings-amaghi-m": toSvgComponent(require("../../assets/questions/custom-greetings-amaghi-m.svg")),
  "custom-greetings-ana-m-amu-igbo": toSvgComponent(require("../../assets/questions/custom-greetings-ana-m-amu-igbo.svg")),
  "custom-greetings-bia-ebe-a": toSvgComponent(require("../../assets/questions/custom-greetings-bia-ebe-a.svg")),
  "custom-greetings-biko-kwuo-ya-ozo": toSvgComponent(require("../../assets/questions/custom-greetings-biko-kwuo-ya-ozo.svg")),
  "custom-asking-questions-ebee-ka-i-na-aga": toSvgComponent(require("../../assets/questions/custom-asking-questions-ebee-ka-i-na-aga.svg")),
  "custom-asking-questions-gini-bu-aha-gi": toSvgComponent(require("../../assets/questions/custom-asking-questions-gini-bu-aha-gi.svg")),
  "custom-asking-questions-gini-mere-i-ji-akwa-akwa": toSvgComponent(require("../../assets/questions/custom-asking-questions-gini-mere-i-ji-akwa-akwa.svg")),
  "custom-asking-questions-onye-bu-onye-ahu": toSvgComponent(require("../../assets/questions/custom-asking-questions-onye-bu-onye-ahu.svg")),
  "custom-animals-anumanu": toSvgComponent(require("../../assets/questions/custom-animals-anumanu.svg")),
  "custom-animals-ehi": toSvgComponent(require("../../assets/questions/custom-animals-ehi.svg")),
  "custom-animals-ewu": toSvgComponent(require("../../assets/questions/custom-animals-ewu.svg")),
  "custom-animals-nkita": toSvgComponent(require("../../assets/questions/custom-animals-nkita.svg")),
  "custom-animals-nnunu": toSvgComponent(require("../../assets/questions/custom-animals-nnunu.svg")),
  "custom-animals-okuko": toSvgComponent(require("../../assets/questions/custom-animals-okuko.svg")),
  "custom-animals-pusi": toSvgComponent(require("../../assets/questions/custom-animals-pusi.svg")),
  "custom-celebrations-agbamakwukwo": toSvgComponent(require("../../assets/questions/custom-celebrations-agbamakwukwo.svg")),
  "custom-celebrations-egwu": toSvgComponent(require("../../assets/questions/custom-celebrations-egwu.svg")),
  "custom-celebrations-emume": toSvgComponent(require("../../assets/questions/custom-celebrations-emume.svg")),
  "custom-celebrations-igu-aha-nwa": toSvgComponent(require("../../assets/questions/custom-celebrations-igu-aha-nwa.svg")),
  "custom-celebrations-iri-ji-ohuru": toSvgComponent(require("../../assets/questions/custom-celebrations-iri-ji-ohuru.svg")),
  "custom-celebrations-oriri": toSvgComponent(require("../../assets/questions/custom-celebrations-oriri.svg")),
  "custom-celebrations-ubochi-omumu": toSvgComponent(require("../../assets/questions/custom-celebrations-ubochi-omumu.svg")),
  "custom-elders-ngozi": toSvgComponent(require("../../assets/questions/custom-elders-ngozi.svg")),
  "custom-elders-nna-ochie": toSvgComponent(require("../../assets/questions/custom-elders-nna-ochie.svg")),
  "custom-elders-nne-ochie": toSvgComponent(require("../../assets/questions/custom-elders-nne-ochie.svg")),
  "custom-elders-nsopuru": toSvgComponent(require("../../assets/questions/custom-elders-nsopuru.svg")),
  "custom-elders-okenye": toSvgComponent(require("../../assets/questions/custom-elders-okenye.svg")),
  "custom-elders-okenye-nwanyi": toSvgComponent(require("../../assets/questions/custom-elders-okenye-nwanyi.svg")),
  "custom-elders-okenye-nwoke": toSvgComponent(require("../../assets/questions/custom-elders-okenye-nwoke.svg")),
  "custom-emotions-anuri": toSvgComponent(require("../../assets/questions/custom-emotions-anuri.svg")),
  "custom-emotions-egwu": toSvgComponent(require("../../assets/questions/custom-emotions-egwu.svg")),
  "custom-emotions-ike-agwula": toSvgComponent(require("../../assets/questions/custom-emotions-ike-agwula.svg")),
  "custom-emotions-iwe": toSvgComponent(require("../../assets/questions/custom-emotions-iwe.svg")),
  "custom-emotions-mwute": toSvgComponent(require("../../assets/questions/custom-emotions-mwute.svg")),
  "custom-emotions-obi-uto": toSvgComponent(require("../../assets/questions/custom-emotions-obi-uto.svg")),
  "custom-emotions-udo": toSvgComponent(require("../../assets/questions/custom-emotions-udo.svg")),
  "custom-family-people-nna": toSvgComponent(require("../../assets/questions/custom-family-people-nna.svg")),
  "custom-family-people-nne": toSvgComponent(require("../../assets/questions/custom-family-people-nne.svg")),
  "custom-family-people-nwanne-nwanyi": toSvgComponent(require("../../assets/questions/custom-family-people-nwanne-nwanyi.svg")),
  "custom-family-people-nwanne-nwoke": toSvgComponent(require("../../assets/questions/custom-family-people-nwanne-nwoke.svg")),
  "custom-food-cooking-mmiri": toSvgComponent(require("../../assets/questions/custom-food-cooking-mmiri.svg")),
  "custom-food-cooking-nri": toSvgComponent(require("../../assets/questions/custom-food-cooking-nri.svg")),
  "custom-food-cooking-ofe": toSvgComponent(require("../../assets/questions/custom-food-cooking-ofe.svg")),
  "custom-food-cooking-osikapa": toSvgComponent(require("../../assets/questions/custom-food-cooking-osikapa.svg")),
  "custom-health-ahuike": toSvgComponent(require("../../assets/questions/custom-health-ahuike.svg")),
  "custom-health-dibia": toSvgComponent(require("../../assets/questions/custom-health-dibia.svg")),
  "custom-health-mgbu": toSvgComponent(require("../../assets/questions/custom-health-mgbu.svg")),
  "custom-health-ogwu": toSvgComponent(require("../../assets/questions/custom-health-ogwu.svg")),
  "custom-health-onye-noosu": toSvgComponent(require("../../assets/questions/custom-health-onye-noosu.svg")),
  "custom-health-oria": toSvgComponent(require("../../assets/questions/custom-health-oria.svg")),
  "custom-health-ulo-ogwu": toSvgComponent(require("../../assets/questions/custom-health-ulo-ogwu.svg")),
  "custom-household-objects-akwa": toSvgComponent(require("../../assets/questions/custom-household-objects-akwa.svg")),
  "custom-household-objects-ime-ulo": toSvgComponent(require("../../assets/questions/custom-household-objects-ime-ulo.svg")),
  "custom-household-objects-oche": toSvgComponent(require("../../assets/questions/custom-household-objects-oche.svg")),
  "custom-household-objects-tebulu": toSvgComponent(require("../../assets/questions/custom-household-objects-tebulu.svg")),
  "custom-household-objects-ulo": toSvgComponent(require("../../assets/questions/custom-household-objects-ulo.svg")),
  "custom-household-objects-windo": toSvgComponent(require("../../assets/questions/custom-household-objects-windo.svg")),
  "custom-numbers-money-abuo": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "custom-numbers-money-ano": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "custom-numbers-money-asaa": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "custom-numbers-money-ato": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "custom-numbers-money-ise": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "custom-numbers-money-isii": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "custom-numbers-money-otu": toSvgComponent(require("../../assets/questions/nouns-money.svg")),
  "custom-school-work-akwukwo": toSvgComponent(require("../../assets/questions/custom-school-work-akwukwo.svg")),
  "custom-school-work-guo": toSvgComponent(require("../../assets/questions/custom-school-work-guo.svg")),
  "custom-school-work-klaasi": toSvgComponent(require("../../assets/questions/custom-school-work-klaasi.svg")),
  "custom-school-work-mkpisi-ide": toSvgComponent(require("../../assets/questions/custom-school-work-mkpisi-ide.svg")),
  "custom-school-work-nwata-akwukwo": toSvgComponent(require("../../assets/questions/custom-school-work-nwata-akwukwo.svg")),
  "custom-school-work-onye-nkuzi": toSvgComponent(require("../../assets/questions/custom-school-work-onye-nkuzi.svg")),
  "custom-school-work-ulo-akwukwo": toSvgComponent(require("../../assets/questions/custom-school-work-ulo-akwukwo.svg")),
  "custom-transportation-igwe-kwu-otu-ebe": toSvgComponent(require("../../assets/questions/custom-transportation-igwe-kwu-otu-ebe.svg")),
  "custom-transportation-okada": toSvgComponent(require("../../assets/questions/custom-transportation-okada.svg")),
  "custom-transportation-onye-na-anya-ugbo-ala": toSvgComponent(require("../../assets/questions/custom-transportation-onye-na-anya-ugbo-ala.svg")),
  "custom-transportation-taksi": toSvgComponent(require("../../assets/questions/custom-transportation-taksi.svg")),
  "custom-transportation-ugbo-ala": toSvgComponent(require("../../assets/questions/custom-transportation-ugbo-ala.svg")),
  "custom-transportation-ugbo-njem": toSvgComponent(require("../../assets/questions/custom-transportation-ugbo-njem.svg")),
  "custom-transportation-uzo": toSvgComponent(require("../../assets/questions/custom-transportation-uzo.svg")),
  "custom-weather-nature-anyanwu": toSvgComponent(require("../../assets/questions/custom-weather-nature-anyanwu.svg")),
  "custom-weather-nature-ifufe": toSvgComponent(require("../../assets/questions/custom-weather-nature-ifufe.svg")),
  "custom-weather-nature-igwe-ojii": toSvgComponent(require("../../assets/questions/custom-weather-nature-igwe-ojii.svg")),
  "custom-weather-nature-ihu-igwe": toSvgComponent(require("../../assets/questions/custom-weather-nature-ihu-igwe.svg")),
  "custom-weather-nature-mmiri-ozuzo": toSvgComponent(require("../../assets/questions/custom-weather-nature-mmiri-ozuzo.svg")),
  "custom-weather-nature-oke-ifufe": toSvgComponent(require("../../assets/questions/custom-weather-nature-oke-ifufe.svg")),
  "custom-weather-nature-oyi": toSvgComponent(require("../../assets/questions/custom-weather-nature-oyi.svg")),
  
  // Sentence breakdown illustrations
  "What is your name": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/What is your name.svg")),
  "How are you": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/How are you.svg")),
  "I want to go home": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/I want to go home.svg")),
  "I do not understand": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/I do not understand.svg")),
  "I am hungry": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/I am hungry.svg")),
  "I have two brothers": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/I have two brothers.svg")),
  "I will come tomorrow": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/I will come tomorrow.svg")),
  "Where is our sister": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/Where is our sister.svg")),
  "They are tired": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/They are tired.svg")),
  "We are thirsty": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/We are thirsty.svg")),
  "Give him water": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/Give him water.svg")),
  "He is going to the river to fetch water": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/He is going to the river to fetch water.svg")),
  "I am going to see my father at the farm": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/I am going to see my father at the farm.svg")),
  "If it rains, we will stay at home": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/If it rains, we will stay at home.svg")),
  "My house is bigger than your house": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/My house is bigger than your house.svg")),
  "Shall we go see them": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/Shall we go see them.svg")),
  "The boy who is playing football is my friend": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/The boy who is playing football is my friend.svg")),
  "They are playing football near the school": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/They are playing football near the school.svg")),
  "They walked a long distance this morning": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/They walked a long distance this morning.svg")),
  "We can go tomorrow": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/We can go tomorrow.svg")),
  "We cannot go home": toSvgComponent(require("../../assets/illustrations/sentence_breakdowns/We cannot go home.svg")),

  // Past, Present & Future Tenses
  "tenses-present-eat": toSvgComponent(require("../../assets/questions/tenses-present-eat.svg")),
  "tenses-present-go": toSvgComponent(require("../../assets/questions/tenses-present-go.svg")),
  "tenses-present-learn": toSvgComponent(require("../../assets/questions/tenses-present-learn.svg")),
  "tenses-past-eat": toSvgComponent(require("../../assets/questions/tenses-past-eat.svg")),
  "tenses-past-go": toSvgComponent(require("../../assets/questions/tenses-past-go.svg")),
  "tenses-past-learn": toSvgComponent(require("../../assets/questions/tenses-past-learn.svg")),
  "tenses-future-eat": toSvgComponent(require("../../assets/questions/tenses-future-eat.svg")),
  "tenses-future-go": toSvgComponent(require("../../assets/questions/tenses-future-go.svg")),
  "tenses-future-learn": toSvgComponent(require("../../assets/questions/tenses-future-learn.svg")),

  // Describing Things (Adjectives)
  "adjectives-big-house": toSvgComponent(require("../../assets/questions/adjectives-big-house.svg")),
  "adjectives-good-person": toSvgComponent(require("../../assets/questions/adjectives-good-person.svg")),
  "adjectives-small-child": toSvgComponent(require("../../assets/questions/adjectives-small-child.svg")),
  "adjectives-beautiful-woman": toSvgComponent(require("../../assets/questions/adjectives-beautiful-woman.svg")),
  "adjectives-house-is-big": toSvgComponent(require("../../assets/questions/adjectives-house-is-big.svg")),
  "adjectives-food-is-good": toSvgComponent(require("../../assets/questions/adjectives-food-is-good.svg")),
  "adjectives-water-is-cold": toSvgComponent(require("../../assets/questions/adjectives-water-is-cold.svg")),
  "adjectives-food-very-good": toSvgComponent(require("../../assets/questions/adjectives-food-very-good.svg")),
  "adjectives-child-strong": toSvgComponent(require("../../assets/questions/adjectives-child-strong.svg")),

  // Time & Dates
  "time-today": toSvgComponent(require("../../assets/questions/time-today.svg")),
  "time-yesterday": toSvgComponent(require("../../assets/questions/time-yesterday.svg")),
  "time-tomorrow": toSvgComponent(require("../../assets/questions/time-tomorrow.svg")),
  "time-oclock": toSvgComponent(require("../../assets/questions/time-oclock.svg")),
  "time-morning": toSvgComponent(require("../../assets/questions/time-morning.svg")),
  "time-evening": toSvgComponent(require("../../assets/questions/time-evening.svg")),
  "time-this-week": toSvgComponent(require("../../assets/questions/time-this-week.svg")),
  "time-last-week": toSvgComponent(require("../../assets/questions/time-last-week.svg")),
  "time-next-week": toSvgComponent(require("../../assets/questions/time-next-week.svg")),

  // Travel & Culture
  "travel-journey": toSvgComponent(require("../../assets/questions/travel-journey.svg")),
  "travel-market": toSvgComponent(require("../../assets/questions/travel-market.svg")),
  "travel-going": toSvgComponent(require("../../assets/questions/travel-going.svg")),
  "travel-village-square": toSvgComponent(require("../../assets/questions/travel-village-square.svg")),
  "travel-family-home": toSvgComponent(require("../../assets/questions/travel-family-home.svg")),
  "travel-sibling": toSvgComponent(require("../../assets/questions/travel-sibling.svg")),
  "travel-celebration": toSvgComponent(require("../../assets/questions/travel-celebration.svg")),
  "travel-visit-family": toSvgComponent(require("../../assets/questions/travel-visit-family.svg")),
  "travel-hometown": toSvgComponent(require("../../assets/questions/travel-hometown.svg")),

  // Opinions & Debate lesson (position 14)
  "opinions-think-good": toSvgComponent(require("../../assets/questions/opinions-think-good.svg")),
  "opinions-igbo-easy": toSvgComponent(require("../../assets/questions/opinions-igbo-easy.svg")),
  "opinions-agree": toSvgComponent(require("../../assets/questions/opinions-agree.svg")),
  "opinions-disagree": toSvgComponent(require("../../assets/questions/opinions-disagree.svg")),
  "opinions-what-think": toSvgComponent(require("../../assets/questions/opinions-what-think.svg")),
  "opinions-because-useful": toSvgComponent(require("../../assets/questions/opinions-because-useful.svg")),
  "opinions-that-true": toSvgComponent(require("../../assets/questions/opinions-that-true.svg")),
  "opinions-that-false": toSvgComponent(require("../../assets/questions/opinions-that-false.svg")),
  "opinions-we-should-go": toSvgComponent(require("../../assets/questions/opinions-we-should-go.svg")),

  // Shopping & Bargaining lesson (position 15)
  "shopping-how-much": toSvgComponent(require("../../assets/questions/shopping-how-much.svg")),
  "shopping-want": toSvgComponent(require("../../assets/questions/shopping-want.svg")),
  "shopping-buying": toSvgComponent(require("../../assets/questions/shopping-buying.svg")),
  "shopping-expensive": toSvgComponent(require("../../assets/questions/shopping-expensive.svg")),
  "shopping-bargaining": toSvgComponent(require("../../assets/questions/shopping-bargaining.svg")),
  "shopping-numbers": toSvgComponent(require("../../assets/questions/shopping-numbers.svg")),
  "shopping-paying": toSvgComponent(require("../../assets/questions/shopping-paying.svg")),
  "shopping-bananas": toSvgComponent(require("../../assets/questions/shopping-bananas.svg")),
  "shopping-bought-shoes": toSvgComponent(require("../../assets/questions/shopping-bought-shoes.svg")),

  // Igbo Idioms and Proverbs lesson (position 16)
  "proverbs-oil-words": toSvgComponent(require("../../assets/questions/proverbs-oil-words.svg")),
  "proverbs-kite-eagle": toSvgComponent(require("../../assets/questions/proverbs-kite-eagle.svg")),
  "proverbs-wash-hands": toSvgComponent(require("../../assets/questions/proverbs-wash-hands.svg")),
  "proverbs-hands-cooperate": toSvgComponent(require("../../assets/questions/proverbs-hands-cooperate.svg")),
  "proverbs-askquestions": toSvgComponent(require("../../assets/questions/proverbs-askquestions.svg")),
  "proverbs-one-tree": toSvgComponent(require("../../assets/questions/proverbs-one-tree.svg")),
  "proverbs-serve-king": toSvgComponent(require("../../assets/questions/proverbs-serve-king.svg")),
  "proverbs-hero-known": toSvgComponent(require("../../assets/questions/proverbs-hero-known.svg")),
  "proverbs-actions-good": toSvgComponent(require("../../assets/questions/proverbs-actions-good.svg")),
};