import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0D0F14",
  },
  scrollView: {
    flex: 1,
    backgroundColor: "#0D0F14",
  },
  homeContent: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 28,
    paddingTop: 56,
    paddingBottom: 0,
  },
  homeTopContent: {
    width: "100%",
    alignItems: "center",
    marginTop: 44,
    marginBottom: 36,
    gap: 72,
  },
  homeHeadline: {
    color: "#F7F7F7",
    textAlign: "center",
    fontFamily: "DMSans_400Regular",
    fontSize: 36,
    lineHeight: 40,
  },
  homeHeroWrap: {
    width: "105%",
    aspectRatio: 0.72,
    maxWidth: 820,
    justifyContent: "center",
    alignItems: "center",
    marginTop: -20,
    marginBottom: -20,
  },
  button: {
    width: "100%",
    maxWidth: 620,
    minHeight: 100,
    borderRadius: 28,
    backgroundColor: "#55BFF2",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  buttonText: {
    color: "#111111",
    fontFamily: "DMSans_700Bold",
    fontSize: 28,
    lineHeight: 36,
  },
  lessonsContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 110,
  },
  lessonsHeaderRow: {
    display: "flex",
    flexDirection: "column",
    flexWrap: "nowrap",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    backgroundColor: "#0D0F14",
    paddingTop: 8,
    paddingBottom: 10,
    paddingHorizontal: 4,
    zIndex: 2,
    marginBottom: 0,
    gap: 8,
  },
  metricsRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
  },
  metricWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  metricText: {
    color: "#FFFFFF",
    fontFamily: "DMSans_700Bold",
    fontSize: 22,
    lineHeight: 24,
  },
  lessonsHeaderCenter: {
    alignItems: "center",
    justifyContent: "center",
  },
  lessonsHeaderLogo: {
    width: 92,
    height: 54,
  },
  lessonList: {
    gap: 22,
    paddingTop: 6,
  },
  lessonCard: {
    minHeight: 106,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#2A2F3A",
    backgroundColor: "#1A1C21",
    paddingHorizontal: 32,
    paddingTop: 30,
    paddingBottom: 22,
    justifyContent: "center",
    overflow: "hidden",
  },
  lessonCardLocked: {
    opacity: 0.72,
  },
  lessonCardTitle: {
    color: "#F4F4F4",
    fontFamily: "DMSans_700Bold",
    fontSize: 21,
    lineHeight: 24,
  },
  lessonCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  lessonCardLockPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#3B4452",
    backgroundColor: "#202734",
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  lessonCardLockPillText: {
    color: "#D4DEEE",
    fontFamily: "DMSans_700Bold",
    fontSize: 11,
    lineHeight: 14,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  lessonCardMeta: {
    marginTop: 6,
    color: "#99A6B4",
    fontFamily: "DMSans_400Regular",
    fontSize: 14,
    lineHeight: 18,
  },
  lessonCardProgressTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 6,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  lessonCardProgressFill: {
    height: "100%",
    backgroundColor: "#4FC3FF",
  },
  fixedFooter: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingBottom: 14,
    paddingTop: 10,
    backgroundColor: "rgba(13, 15, 20, 0.98)",
    borderTopWidth: 1,
    borderTopColor: "#1E2633",
  },
  loginFooterButton: {
    width: "100%",
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "#0F7AD6",
    borderWidth: 1,
    borderColor: "#4FA5EC",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  loginFooterButtonText: {
    color: "#FFFFFF",
    fontFamily: "DMSans_700Bold",
    fontSize: 16,
    lineHeight: 20,
  },
  premiumFooterRow: {
    width: "100%",
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  premiumBadgeChip: {
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: "#203427",
    borderWidth: 1,
    borderColor: "#4C9F62",
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  premiumBadgeText: {
    color: "#B8F3C7",
    fontFamily: "DMSans_700Bold",
    fontSize: 13,
    lineHeight: 16,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  avatarButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#264A82",
    borderWidth: 1,
    borderColor: "#4FA5EC",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: "#FFFFFF",
    fontFamily: "DMSans_700Bold",
    fontSize: 18,
    lineHeight: 20,
  },
  accountPopover: {
    position: "absolute",
    right: 18,
    bottom: 74,
    width: 230,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#181C23",
    padding: 10,
    gap: 8,
  },
  accountPopoverEmail: {
    color: "#DDE7F1",
    fontFamily: "DMSans_400Regular",
    fontSize: 13,
    lineHeight: 17,
  },
  accountPopoverSecondaryButton: {
    minHeight: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2F3B4B",
    backgroundColor: "#1E2530",
    alignItems: "center",
    justifyContent: "center",
  },
  accountPopoverSecondaryText: {
    color: "#D9E8FA",
    fontFamily: "DMSans_700Bold",
    fontSize: 13,
    lineHeight: 16,
  },
  accountPopoverLogout: {
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: "#26303D",
    alignItems: "center",
    justifyContent: "center",
  },
  accountPopoverLogoutText: {
    color: "#F0F6FF",
    fontFamily: "DMSans_700Bold",
    fontSize: 14,
    lineHeight: 16,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  loadingCard: {
    minWidth: 220,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#151A22",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  loadingText: {
    color: "#DDE7F1",
    fontFamily: "DMSans_700Bold",
    fontSize: 14,
    lineHeight: 18,
  },
  quizFlowContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 112,
  },
  quizTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  quizBackIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#3A3B3F",
    alignItems: "center",
    justifyContent: "center",
  },
  quizHeaderProgressTrack: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#45484D",
    overflow: "hidden",
  },
  quizHeaderProgressFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: "#9CD754",
  },
  speakerButton: {
    marginTop: 0,
    width: 66,
    height: 66,
    borderRadius: 33,
    alignSelf: "center",
    backgroundColor: "#3A3B3F",
    alignItems: "center",
    justifyContent: "center",
  },
  speakerButtonDisabled: {
    opacity: 0.7,
  },
  speakerSkeletonGlyph: {
    width: 34,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#66717E",
  },
  speakerControlsRow: {
    marginTop: 22,
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    gap: 10,
  },
  speakerControlsRowCompact: {
    marginTop: 10,
  },
  speedToggleButton: {
    minHeight: 36,
    minWidth: 66,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#181C23",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  speedToggleButtonDisabled: {
    opacity: 0.6,
  },
  speedToggleText: {
    color: "#DDE7F1",
    fontFamily: "DMSans_700Bold",
    fontSize: 12,
    lineHeight: 14,
  },
  quizPromptRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  quizPromptRowCompact: {
    marginTop: 8,
  },
  quizPromptWord: {
    color: "#FFFFFF",
    fontFamily: "DMSans_400Regular",
    fontSize: 18,
    lineHeight: 22,
  },
  quizPromptWordCompact: {
    fontSize: 17,
    lineHeight: 21,
  },
  hintIconButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3A3B3F",
  },
  quizIllustrationSlot: {
    marginTop: 10,
    height: 120,
    alignItems: "center",
    justifyContent: "center",
  },
  storyModeWrap: {
    marginTop: 18,
    alignItems: "center",
  },
  storyBubbleWrap: {
    width: "100%",
    maxWidth: 320,
  },
  storyBubbleWrapLeft: {
    alignItems: "flex-start",
  },
  storyBubbleWrapRight: {
    alignItems: "flex-end",
  },
  storyBubble: {
    width: "100%",
    minHeight: 92,
    borderRadius: 28,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingVertical: 16,
    justifyContent: "center",
  },
  storyBubbleIgbo: {
    color: "#111111",
    textAlign: "center",
    fontFamily: "DMSans_700Bold",
    fontSize: 22,
    lineHeight: 27,
  },
  storyBubbleEnglish: {
    marginTop: 6,
    color: "#536172",
    textAlign: "center",
    fontFamily: "DMSans_400Regular",
    fontSize: 14,
    lineHeight: 18,
  },
  storyBubbleTail: {
    width: 0,
    height: 0,
    borderTopWidth: 16,
    borderTopColor: "#FFFFFF",
    borderLeftWidth: 12,
    borderLeftColor: "transparent",
    borderRightWidth: 12,
    borderRightColor: "transparent",
    marginTop: -1,
  },
  storyBubbleTailLeft: {
    marginLeft: 22,
  },
  storyBubbleTailRight: {
    marginRight: 22,
  },
  storyCharactersRow: {
    width: "100%",
    marginTop: 20,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 18,
  },
  storyCharacterWrap: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 6,
  },
  storyCharacterWrapActive: {
    transform: [{ scale: 1.03 }],
  },
  storyCharacterIllustrationWrap: {
    width: 104,
    height: 104,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  storyCharacterLabel: {
    marginTop: 8,
    color: "#DDE7F1",
    fontFamily: "DMSans_700Bold",
    fontSize: 14,
    lineHeight: 18,
  },
  storyStatementText: {
    marginTop: 24,
    color: "#FFFFFF",
    textAlign: "center",
    fontFamily: "DMSans_400Regular",
    fontSize: 18,
    lineHeight: 24,
  },
  storyChoiceRow: {
    width: "100%",
    marginTop: 22,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  storyChoiceButton: {
    flex: 1,
    minHeight: 100,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#333A46",
    backgroundColor: "#1B1B1E",
    alignItems: "center",
    justifyContent: "center",
  },
  storyChoiceButtonSelected: {
    borderColor: "#4EC5FF",
    backgroundColor: "#1C2E3B",
  },
  storyChoiceButtonText: {
    color: "#FFFFFF",
    fontFamily: "DMSans_700Bold",
    fontSize: 24,
    lineHeight: 28,
  },
  storyChoiceButtonTextSelected: {
    color: "#DDF5FF",
  },
  sentenceBuilderWrap: {
    marginTop: 14,
    gap: 10,
    paddingHorizontal: 4,
  },
  sentenceBuilderWrapCompact: {
    marginTop: 8,
    gap: 6,
    paddingHorizontal: 2,
  },
  sentenceSourceCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#181C23",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sentenceSourceCardCompact: {
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  sentenceSourceText: {
    color: "#F4F7FA",
    textAlign: "center",
    fontFamily: "DMSans_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  slotGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
  },
  slotGridCompact: {
    gap: 7,
  },
  slotChip: {
    minWidth: 108,
    minHeight: 58,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#2A2F3A",
    borderStyle: "dashed",
    backgroundColor: "#10141B",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  slotChipCompact: {
    minWidth: 94,
    minHeight: 50,
    borderRadius: 13,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  slotChipFilled: {
    borderStyle: "solid",
    borderColor: "#4EC5FF",
    backgroundColor: "#172634",
  },
  slotChipActive: {
    borderColor: "#F7C654",
    backgroundColor: "#2E2412",
  },
  slotChipText: {
    color: "#5E6F83",
    fontFamily: "DMSans_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  slotChipTextCompact: {
    fontSize: 16,
    lineHeight: 20,
  },
  slotChipTextFilled: {
    color: "#F2FAFF",
  },
  sentenceBuilderHelperText: {
    color: "#7E91A6",
    textAlign: "center",
    fontFamily: "DMSans_400Regular",
    fontSize: 12,
    lineHeight: 16,
    marginTop: -2,
  },
  sentenceHelperText: {
    color: "#97A9BC",
    textAlign: "center",
    fontFamily: "DMSans_400Regular",
    fontSize: 14,
    lineHeight: 18,
  },
  wordBankWrap: {
    marginTop: 10,
    marginHorizontal: 6,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 30,
  },
  wordBankWrapCompact: {
    marginTop: 8,
    marginHorizontal: 4,
    gap: 21,
  },
  wordBankChip: {
    minHeight: 56,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#181C23",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 18,
  },
  wordBankChipCompact: {
    minHeight: 48,
    borderRadius: 21,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  wordBankChipDisabled: {
    opacity: 0.35,
  },
  wordBankChipText: {
    color: "#F3F7FB",
    fontFamily: "DMSans_700Bold",
    fontSize: 16,
    lineHeight: 20,
  },
  wordBankChipTextCompact: {
    fontSize: 13,
    lineHeight: 17,
  },
  wordBankChipTextDisabled: {
    color: "#8A97A6",
  },
  answerInputWrap: {
    marginTop: 24,
    gap: 18,
  },
  multipleChoiceList: {
    marginTop: 20,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  choiceCard: {
    width: "48%",
    minHeight: 112,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#181C23",
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
  },
  choiceCardSelected: {
    borderColor: "#4EC5FF",
    backgroundColor: "#1C2E3B",
  },
  choiceLabel: {
    color: "#F3F7FB",
    fontFamily: "DMSans_700Bold",
    fontSize: 22,
    lineHeight: 26,
    textAlign: "center",
  },
  choiceLabelSelected: {
    color: "#DDF5FF",
  },
  choiceTranslation: {
    marginTop: 2,
    color: "#97A7B8",
    fontFamily: "DMSans_400Regular",
    fontSize: 13,
    lineHeight: 17,
    textAlign: "center",
  },
  choiceTranslationSelected: {
    color: "#AEDDFF",
  },
  answerInput: {
    color: "#E7F7FF",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "500",
    paddingVertical: 0,
  },
  answerLine: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "#4EC5FF",
  },
  hintText: {
    marginTop: 26,
    color: "#8BD0FF",
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "600",
  },
  quizBottomSpacer: {
    minHeight: 4,
  },
  checkButtonFixedWrap: {
    position: "absolute",
    left: 24,
    right: 24,
    bottom: 16,
  },
  checkButton: {
    marginTop: 0,
    marginBottom: 4,
    minHeight: 68,
    borderRadius: 20,
    backgroundColor: "#3CC1FF",
    alignItems: "center",
    justifyContent: "center",
  },
  checkButtonCompact: {
    minHeight: 56,
    borderRadius: 16,
  },
  checkButtonText: {
    color: "#0C1721",
    fontSize: 31,
    lineHeight: 35,
    fontWeight: "800",
  },
  checkButtonTextCompact: {
    fontSize: 24,
    lineHeight: 28,
  },
  feedbackSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  feedbackSheetCorrect: {
    backgroundColor: "#BEE3A6",
  },
  feedbackSheetWrong: {
    backgroundColor: "#E0C8CA",
  },
  feedbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 14,
  },
  feedbackIconCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackIconCircleCorrect: {
    backgroundColor: "#39A600",
  },
  feedbackIconCircleWrong: {
    backgroundColor: "#EF2C33",
  },
  feedbackIconText: {
    color: "#FFFFFF",
    fontSize: 26,
    lineHeight: 30,
    fontWeight: "700",
  },
  feedbackTitle: {
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "700",
  },
  feedbackTitleCorrect: {
    color: "#33980C",
  },
  feedbackTitleWrong: {
    color: "#EA2E35",
  },
  feedbackAnswerText: {
    textAlign: "center",
    color: "#7A2124",
    fontFamily: "DMSans_400Regular",
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 12,
  },
  feedbackAction: {
    minHeight: 72,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  feedbackActionCorrect: {
    backgroundColor: "#56CD00",
  },
  feedbackActionWrong: {
    backgroundColor: "#FF4B54",
  },
  feedbackActionDisabled: {
    opacity: 0.72,
  },
  feedbackActionText: {
    color: "#FFFFFF",
    fontSize: 38,
    lineHeight: 42,
    fontWeight: "700",
  },
  hintModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingHorizontal: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  hintModalCard: {
    width: "100%",
    maxHeight: "80%",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#2A2F3A",
    backgroundColor: "#15181E",
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  hintModalTitle: {
    color: "#F5F7FA",
    textAlign: "center",
    fontFamily: "DMSans_700Bold",
    fontSize: 24,
    lineHeight: 28,
    marginBottom: 14,
  },
  hintModalList: {
    maxHeight: 420,
  },
  hintModalRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#252A33",
    gap: 4,
  },
  hintWord: {
    color: "#FFFFFF",
    fontFamily: "DMSans_700Bold",
    fontSize: 16,
    lineHeight: 20,
  },
  hintMeaning: {
    color: "#99A6B4",
    fontFamily: "DMSans_400Regular",
    fontSize: 14,
    lineHeight: 18,
  },
  hintModalCloseButton: {
    marginTop: 18,
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "#4FC3FF",
    alignItems: "center",
    justifyContent: "center",
  },
  hintModalCloseText: {
    color: "#07141E",
    fontFamily: "DMSans_700Bold",
    fontSize: 20,
    lineHeight: 24,
  },
  upgradeModalCard: {
    width: "100%",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#2A2F3A",
    backgroundColor: "#15181E",
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  upgradeModalTitle: {
    color: "#F5F7FA",
    textAlign: "center",
    fontFamily: "DMSans_700Bold",
    fontSize: 24,
    lineHeight: 28,
  },
  upgradeModalText: {
    marginTop: 8,
    color: "#99A6B4",
    textAlign: "center",
    fontFamily: "DMSans_400Regular",
    fontSize: 14,
    lineHeight: 20,
  },
  upgradeEmailInput: {
    marginTop: 16,
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#181C23",
    color: "#F3F7FB",
    fontFamily: "DMSans_400Regular",
    fontSize: 16,
    paddingHorizontal: 14,
  },
  upgradeSubmitButton: {
    marginTop: 14,
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "#4FC3FF",
    alignItems: "center",
    justifyContent: "center",
  },
  upgradeSubmitText: {
    color: "#07141E",
    fontFamily: "DMSans_700Bold",
    fontSize: 17,
    lineHeight: 20,
  },
  upgradeCancelButton: {
    marginTop: 10,
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#2B313D",
    backgroundColor: "#181C23",
    alignItems: "center",
    justifyContent: "center",
  },
  upgradeCancelText: {
    color: "#D7E0EA",
    fontFamily: "DMSans_700Bold",
    fontSize: 15,
    lineHeight: 18,
  },
  completedContent: {
    flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: 24,
    justifyContent: "center",
    paddingTop: 16,
    paddingBottom: 20,
  },
  completedTitle: {
    color: "#F7F7F7",
    textAlign: "center",
    fontSize: 42,
    lineHeight: 46,
    fontWeight: "800",
    letterSpacing: -0.6,
    maxWidth: 420,
  },
  completedSubtitle: {
    marginTop: 8,
    color: "#7BCDF8",
    textAlign: "center",
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "600",
  },
  completedIllustrationWrap: {
    width: "100%",
    maxWidth: 330,
    height: 180,
    marginTop: 12,
    marginBottom: 18,
  },
  restartButton: {
    width: "100%",
    maxWidth: 320,
    minHeight: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#3A97C5",
    backgroundColor: "rgba(72, 192, 247, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 48,
    marginBottom: 48,
  },
  restartButtonText: {
    color: "#7BBEDC",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "600",
  },
  continueButton: {
    width: "100%",
    maxWidth: 320,
    minHeight: 62,
    borderRadius: 18,
    backgroundColor: "#48B8EE",
    alignItems: "center",
    justifyContent: "center",
  },
  continueButtonText: {
    color: "#0F1A22",
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "700",
  },
});