// Auto-generated audio mappings for sentence breakdown questions
// Generated by: npm run tts:sentence-breakdowns and npm run tts:sentence-breakdowns-igbo
// DO NOT EDIT MANUALLY

// English pronunciation audio
export const SENTENCE_BREAKDOWNS_AUDIO: Record<string, number> = {
  // Introduction to Igbo lesson (10)
  "what-is-your-name": require("../../assets/audio/sentence_breakdowns/what-is-your-name.m4a"),
  "how-are-you": require("../../assets/audio/sentence_breakdowns/how-are-you.m4a"),
  "i-want-to-go-home": require("../../assets/audio/sentence_breakdowns/i-want-to-go-home.m4a"),
  "i-do-not-understand": require("../../assets/audio/sentence_breakdowns/i-do-not-understand.m4a"),
  "i-am-hungry": require("../../assets/audio/sentence_breakdowns/i-am-hungry.m4a"),
  "i-have-two-brothers": require("../../assets/audio/sentence_breakdowns/i-have-two-brothers.m4a"),
  "i-will-come-tomorrow": require("../../assets/audio/sentence_breakdowns/i-will-come-tomorrow.m4a"),
  "where-is-our-sister": require("../../assets/audio/sentence_breakdowns/where-is-our-sister.m4a"),
  "they-are-tired": require("../../assets/audio/sentence_breakdowns/they-are-tired.m4a"),
  "we-are-thirsty": require("../../assets/audio/sentence_breakdowns/we-are-thirsty.m4a"),
  
  // Getting Started lesson (11)
  "give-him-water": require("../../assets/audio/sentence_breakdowns/give-him-water.m4a"),
  "he-is-going-to-the-river-to-fetch-water": require("../../assets/audio/sentence_breakdowns/he-is-going-to-the-river-to-fetch-water.m4a"),
  "i-am-going-to-see-my-father-at-the-farm": require("../../assets/audio/sentence_breakdowns/i-am-going-to-see-my-father-at-the-farm.m4a"),
  "if-it-rains-we-will-stay-at-home": require("../../assets/audio/sentence_breakdowns/if-it-rains-we-will-stay-at-home.m4a"),
  "my-house-is-bigger-than-your-house": require("../../assets/audio/sentence_breakdowns/my-house-is-bigger-than-your-house.m4a"),
  "shall-we-go-see-them": require("../../assets/audio/sentence_breakdowns/shall-we-go-see-them.m4a"),
  "the-boy-who-is-playing-football-is-my-friend": require("../../assets/audio/sentence_breakdowns/the-boy-who-is-playing-football-is-my-friend.m4a"),
  "they-are-playing-football-near-the-school": require("../../assets/audio/sentence_breakdowns/they-are-playing-football-near-the-school.m4a"),
  "they-walked-a-long-distance-this-morning": require("../../assets/audio/sentence_breakdowns/they-walked-a-long-distance-this-morning.m4a"),
  "we-can-go-tomorrow": require("../../assets/audio/sentence_breakdowns/we-can-go-tomorrow.m4a"),
  "we-cannot-go-home": require("../../assets/audio/sentence_breakdowns/we-cannot-go-home.m4a"),
};

// Igbo pronunciation audio (WAV format)
export const SENTENCE_BREAKDOWNS_IGBO_AUDIO: Record<string, number> = {
  // Introduction to Igbo lesson (10)
  "what-is-your-name": require("../../assets/audio/sentence_breakdowns_igbo/what-is-your-name.wav"),
  "how-are-you": require("../../assets/audio/sentence_breakdowns_igbo/how-are-you.wav"),
  "i-want-to-go-home": require("../../assets/audio/sentence_breakdowns_igbo/i-want-to-go-home.wav"),
  "i-do-not-understand": require("../../assets/audio/sentence_breakdowns_igbo/i-do-not-understand.wav"),
  "i-am-hungry": require("../../assets/audio/sentence_breakdowns_igbo/i-am-hungry.wav"),
  "i-have-two-brothers": require("../../assets/audio/sentence_breakdowns_igbo/i-have-two-brothers.wav"),
  "i-will-come-tomorrow": require("../../assets/audio/sentence_breakdowns_igbo/i-will-come-tomorrow.wav"),
  "where-is-our-sister": require("../../assets/audio/sentence_breakdowns_igbo/where-is-our-sister.wav"),
  "they-are-tired": require("../../assets/audio/sentence_breakdowns_igbo/they-are-tired.wav"),
  "we-are-thirsty": require("../../assets/audio/sentence_breakdowns_igbo/we-are-thirsty.wav"),
  
  // Getting Started lesson (11)
  "give-him-water": require("../../assets/audio/sentence_breakdowns_igbo/give-him-water.wav"),
  "he-is-going-to-the-river-to-fetch-water": require("../../assets/audio/sentence_breakdowns_igbo/he-is-going-to-the-river-to-fetch-water.wav"),
  "i-am-going-to-see-my-father-at-the-farm": require("../../assets/audio/sentence_breakdowns_igbo/i-am-going-to-see-my-father-at-the-farm.wav"),
  "if-it-rains-we-will-stay-at-home": require("../../assets/audio/sentence_breakdowns_igbo/if-it-rains-we-will-stay-at-home.wav"),
  "my-house-is-bigger-than-your-house": require("../../assets/audio/sentence_breakdowns_igbo/my-house-is-bigger-than-your-house.wav"),
  "shall-we-go-see-them": require("../../assets/audio/sentence_breakdowns_igbo/shall-we-go-see-them.wav"),
  "the-boy-who-is-playing-football-is-my-friend": require("../../assets/audio/sentence_breakdowns_igbo/the-boy-who-is-playing-football-is-my-friend.wav"),
  "they-are-playing-football-near-the-school": require("../../assets/audio/sentence_breakdowns_igbo/they-are-playing-football-near-the-school.wav"),
  "they-walked-a-long-distance-this-morning": require("../../assets/audio/sentence_breakdowns_igbo/they-walked-a-long-distance-this-morning.wav"),
  "we-can-go-tomorrow": require("../../assets/audio/sentence_breakdowns_igbo/we-can-go-tomorrow.wav"),
  "we-cannot-go-home": require("../../assets/audio/sentence_breakdowns_igbo/we-cannot-go-home.wav"),

  // Past, Present & Future Tenses lesson (position 10)
  "i-am-eating-food": require("../../assets/audio/sentence_breakdowns_igbo/i-am-eating-food.wav"),
  "i-am-going-home": require("../../assets/audio/sentence_breakdowns_igbo/i-am-going-home.wav"),
  "i-am-learning-igbo": require("../../assets/audio/sentence_breakdowns_igbo/i-am-learning-igbo.wav"),
  "i-ate-food": require("../../assets/audio/sentence_breakdowns_igbo/i-ate-food.wav"),
  "i-went-home": require("../../assets/audio/sentence_breakdowns_igbo/i-went-home.wav"),
  "i-learned-igbo": require("../../assets/audio/sentence_breakdowns_igbo/i-learned-igbo.wav"),
  "i-will-eat-food": require("../../assets/audio/sentence_breakdowns_igbo/i-will-eat-food.wav"),
  "i-will-go-home": require("../../assets/audio/sentence_breakdowns_igbo/i-will-go-home.wav"),
  "i-will-learn-igbo": require("../../assets/audio/sentence_breakdowns_igbo/i-will-learn-igbo.wav"),

  // Describing Things (Adjectives) lesson (position 11)
  "big-house": require("../../assets/audio/sentence_breakdowns_igbo/big-house.wav"),
  "good-person": require("../../assets/audio/sentence_breakdowns_igbo/good-person.wav"),
  "small-child": require("../../assets/audio/sentence_breakdowns_igbo/small-child.wav"),
  "beautiful-woman": require("../../assets/audio/sentence_breakdowns_igbo/beautiful-woman.wav"),
  "the-house-is-big": require("../../assets/audio/sentence_breakdowns_igbo/the-house-is-big.wav"),
  "the-food-is-good": require("../../assets/audio/sentence_breakdowns_igbo/the-food-is-good.wav"),
  "the-water-is-cold": require("../../assets/audio/sentence_breakdowns_igbo/the-water-is-cold.wav"),
  "the-food-is-very-good": require("../../assets/audio/sentence_breakdowns_igbo/the-food-is-very-good.wav"),
  "the-child-is-strong": require("../../assets/audio/sentence_breakdowns_igbo/the-child-is-strong.wav"),

  // Time & Dates lesson (position 12)
  "learning-igbo-today": require("../../assets/audio/sentence_breakdowns_igbo/learning-igbo-today.wav"),
  "went-to-market-yesterday": require("../../assets/audio/sentence_breakdowns_igbo/went-to-market-yesterday.wav"),
  "will-go-tomorrow": require("../../assets/audio/sentence_breakdowns_igbo/will-go-tomorrow.wav"),
  "will-come-at-3": require("../../assets/audio/sentence_breakdowns_igbo/will-come-at-3.wav"),
  "work-in-morning": require("../../assets/audio/sentence_breakdowns_igbo/work-in-morning.wav"),
  "meet-in-evening": require("../../assets/audio/sentence_breakdowns_igbo/meet-in-evening.wav"),
  "learning-igbo-this-week": require("../../assets/audio/sentence_breakdowns_igbo/learning-igbo-this-week.wav"),
  "went-market-last-week": require("../../assets/audio/sentence_breakdowns_igbo/went-market-last-week.wav"),
  "start-new-job-next-week": require("../../assets/audio/sentence_breakdowns_igbo/start-new-job-next-week.wav"),

  // Travel & Culture lesson (position 13)
  "i-am-travelling": require("../../assets/audio/sentence_breakdowns_igbo/i-am-travelling.wav"),
  "where-is-the-market": require("../../assets/audio/sentence_breakdowns_igbo/where-is-the-market.wav"),
  "i-am-going-to-town": require("../../assets/audio/sentence_breakdowns_igbo/i-am-going-to-town.wav"),
  "we-will-meet-at-village-square": require("../../assets/audio/sentence_breakdowns_igbo/we-will-meet-at-village-square.wav"),
  "my-father-is-at-family-compound": require("../../assets/audio/sentence_breakdowns_igbo/my-father-is-at-family-compound.wav"),
  "i-will-visit-my-sibling": require("../../assets/audio/sentence_breakdowns_igbo/i-will-visit-my-sibling.wav"),
  "the-celebration-was-beautiful": require("../../assets/audio/sentence_breakdowns_igbo/the-celebration-was-beautiful.wav"),
  "i-will-visit-my-family": require("../../assets/audio/sentence_breakdowns_igbo/i-will-visit-my-family.wav"),
  "i-am-going-to-my-fathers-hometown": require("../../assets/audio/sentence_breakdowns_igbo/i-am-going-to-my-fathers-hometown.wav"),

  // Opinions & Debate lesson (position 14)
  "i-think-it-is-good": require("../../assets/audio/sentence_breakdowns_igbo/i-think-it-is-good.wav"),
  "in-my-opinion-igbo-easy": require("../../assets/audio/sentence_breakdowns_igbo/in-my-opinion-igbo-easy.wav"),
  "i-agree-with-you": require("../../assets/audio/sentence_breakdowns_igbo/i-agree-with-you.wav"),
  "i-disagree": require("../../assets/audio/sentence_breakdowns_igbo/i-disagree.wav"),
  "what-do-you-think": require("../../assets/audio/sentence_breakdowns_igbo/what-do-you-think.wav"),
  "i-think-because-useful": require("../../assets/audio/sentence_breakdowns_igbo/i-think-because-useful.wav"),
  "that-is-true": require("../../assets/audio/sentence_breakdowns_igbo/that-is-true.wav"),
  "that-is-false": require("../../assets/audio/sentence_breakdowns_igbo/that-is-false.wav"),
  "i-think-we-should-go": require("../../assets/audio/sentence_breakdowns_igbo/i-think-we-should-go.wav"),
};

export const SENTENCE_BREAKDOWNS_EXAMPLE_IGBO_AUDIO: Record<string, number> = {
  "what-is-your-name-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/what-is-your-name-example.wav"),
  "how-are-you-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/how-are-you-example.wav"),
  "i-want-to-go-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-want-to-go-home-example.wav"),
  "i-do-not-understand-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-do-not-understand-example.wav"),
  "i-am-hungry-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-hungry-example.wav"),
  "i-have-two-brothers-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-have-two-brothers-example.wav"),
  "i-will-come-tomorrow-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-will-come-tomorrow-example.wav"),
  "where-is-our-sister-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/where-is-our-sister-example.wav"),
  "they-are-tired-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/they-are-tired-example.wav"),
  "we-are-thirsty-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/we-are-thirsty-example.wav"),
  "give-him-water-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/give-him-water-example.wav"),
  "he-is-going-to-the-river-to-fetch-water-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/he-is-going-to-the-river-to-fetch-water-example.wav"),
  "i-am-going-to-see-my-father-at-the-farm-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-going-to-see-my-father-at-the-farm-example.wav"),
  "if-it-rains-we-will-stay-at-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/if-it-rains-we-will-stay-at-home-example.wav"),
  "my-house-is-bigger-than-your-house-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/my-house-is-bigger-than-your-house-example.wav"),
  "shall-we-go-see-them-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/shall-we-go-see-them-example.wav"),
  "the-boy-who-is-playing-football-is-my-friend-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-boy-who-is-playing-football-is-my-friend-example.wav"),
  "they-are-playing-football-near-the-school-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/they-are-playing-football-near-the-school-example.wav"),
  "they-walked-a-long-distance-this-morning-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/they-walked-a-long-distance-this-morning-example.wav"),
  "we-can-go-tomorrow-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/we-can-go-tomorrow-example.wav"),
  "we-cannot-go-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/we-cannot-go-home-example.wav"),

  // Past, Present & Future Tenses lesson (position 10)
  "i-am-eating-food-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-eating-food-example.wav"),
  "i-am-going-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-going-home-example.wav"),
  "i-am-learning-igbo-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-learning-igbo-example.wav"),
  "i-ate-food-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-ate-food-example.wav"),
  "i-went-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-went-home-example.wav"),
  "i-learned-igbo-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-learned-igbo-example.wav"),
  "i-will-eat-food-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-will-eat-food-example.wav"),
  "i-will-go-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-will-go-home-example.wav"),
  "i-will-learn-igbo-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-will-learn-igbo-example.wav"),

  // Describing Things (Adjectives) lesson (position 11)
  "big-house-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/big-house-example.wav"),
  "good-person-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/good-person-example.wav"),
  "small-child-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/small-child-example.wav"),
  "beautiful-woman-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/beautiful-woman-example.wav"),
  "the-house-is-big-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-house-is-big-example.wav"),
  "the-food-is-good-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-food-is-good-example.wav"),
  "the-water-is-cold-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-water-is-cold-example.wav"),
  "the-food-is-very-good-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-food-is-very-good-example.wav"),
  "the-child-is-strong-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-child-is-strong-example.wav"),

  // Time & Dates lesson (position 12)
  "learning-igbo-today-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/learning-igbo-today-example.wav"),
  "went-to-market-yesterday-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/went-to-market-yesterday-example.wav"),
  "will-go-tomorrow-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/will-go-tomorrow-example.wav"),
  "will-come-at-3-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/will-come-at-3-example.wav"),
  "work-in-morning-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/work-in-morning-example.wav"),
  "meet-in-evening-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/meet-in-evening-example.wav"),
  "learning-igbo-this-week-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/learning-igbo-this-week-example.wav"),
  "went-market-last-week-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/went-market-last-week-example.wav"),
  "start-new-job-next-week-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/start-new-job-next-week-example.wav"),

  // Travel & Culture lesson (position 13)
  "i-am-travelling-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-travelling-example.wav"),
  "where-is-the-market-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/where-is-the-market-example.wav"),
  "i-am-going-to-town-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-going-to-town-example.wav"),
  "we-will-meet-at-village-square-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/we-will-meet-at-village-square-example.wav"),
  "my-father-is-at-family-compound-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/my-father-is-at-family-compound-example.wav"),
  "i-will-visit-my-sibling-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-will-visit-my-sibling-example.wav"),
  "the-celebration-was-beautiful-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-celebration-was-beautiful-example.wav"),
  "i-will-visit-my-family-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-will-visit-my-family-example.wav"),
  "i-am-going-to-my-fathers-hometown-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-going-to-my-fathers-hometown-example.wav"),

  // Opinions & Debate lesson (position 14)
  "i-think-it-is-good-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-think-it-is-good-example.wav"),
  "in-my-opinion-igbo-easy-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/in-my-opinion-igbo-easy-example.wav"),
  "i-agree-with-you-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-agree-with-you-example.wav"),
  "i-disagree-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-disagree-example.wav"),
  "what-do-you-think-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/what-do-you-think-example.wav"),
  "i-think-because-useful-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-think-because-useful-example.wav"),
  "that-is-true-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/that-is-true-example.wav"),
  "that-is-false-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/that-is-false-example.wav"),
  "i-think-we-should-go-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-think-we-should-go-example.wav"),
};

