// Auto-generated audio mappings for sentence breakdown questions
// Generated by: npm run tts:sentence-breakdowns and npm run tts:sentence-breakdowns-igbo
// DO NOT EDIT MANUALLY

// English pronunciation audio
export const SENTENCE_BREAKDOWNS_AUDIO: Record<string, number> = {
  // Introduction to Igbo lesson (10)
  "what-is-your-name": require("../../assets/audio/sentence_breakdowns/what-is-your-name.m4a"),
  "how-are-you": require("../../assets/audio/sentence_breakdowns/how-are-you.m4a"),
  "i-want-to-go-home": require("../../assets/audio/sentence_breakdowns/i-want-to-go-home.m4a"),
  "i-do-not-understand": require("../../assets/audio/sentence_breakdowns/i-do-not-understand.m4a"),
  "i-am-hungry": require("../../assets/audio/sentence_breakdowns/i-am-hungry.m4a"),
  "i-have-two-brothers": require("../../assets/audio/sentence_breakdowns/i-have-two-brothers.m4a"),
  "i-will-come-tomorrow": require("../../assets/audio/sentence_breakdowns/i-will-come-tomorrow.m4a"),
  "where-is-our-sister": require("../../assets/audio/sentence_breakdowns/where-is-our-sister.m4a"),
  "they-are-tired": require("../../assets/audio/sentence_breakdowns/they-are-tired.m4a"),
  "we-are-thirsty": require("../../assets/audio/sentence_breakdowns/we-are-thirsty.m4a"),
  
  // Getting Started lesson (11)
  "give-him-water": require("../../assets/audio/sentence_breakdowns/give-him-water.m4a"),
  "he-is-going-to-the-river-to-fetch-water": require("../../assets/audio/sentence_breakdowns/he-is-going-to-the-river-to-fetch-water.m4a"),
  "i-am-going-to-see-my-father-at-the-farm": require("../../assets/audio/sentence_breakdowns/i-am-going-to-see-my-father-at-the-farm.m4a"),
  "if-it-rains-we-will-stay-at-home": require("../../assets/audio/sentence_breakdowns/if-it-rains-we-will-stay-at-home.m4a"),
  "my-house-is-bigger-than-your-house": require("../../assets/audio/sentence_breakdowns/my-house-is-bigger-than-your-house.m4a"),
  "shall-we-go-see-them": require("../../assets/audio/sentence_breakdowns/shall-we-go-see-them.m4a"),
  "the-boy-who-is-playing-football-is-my-friend": require("../../assets/audio/sentence_breakdowns/the-boy-who-is-playing-football-is-my-friend.m4a"),
  "they-are-playing-football-near-the-school": require("../../assets/audio/sentence_breakdowns/they-are-playing-football-near-the-school.m4a"),
  "they-walked-a-long-distance-this-morning": require("../../assets/audio/sentence_breakdowns/they-walked-a-long-distance-this-morning.m4a"),
  "we-can-go-tomorrow": require("../../assets/audio/sentence_breakdowns/we-can-go-tomorrow.m4a"),
  "we-cannot-go-home": require("../../assets/audio/sentence_breakdowns/we-cannot-go-home.m4a"),
};

// Igbo pronunciation audio (WAV format)
export const SENTENCE_BREAKDOWNS_IGBO_AUDIO: Record<string, number> = {
  // Introduction to Igbo lesson (10)
  "what-is-your-name": require("../../assets/audio/sentence_breakdowns_igbo/what-is-your-name.wav"),
  "how-are-you": require("../../assets/audio/sentence_breakdowns_igbo/how-are-you.wav"),
  "i-want-to-go-home": require("../../assets/audio/sentence_breakdowns_igbo/i-want-to-go-home.wav"),
  "i-do-not-understand": require("../../assets/audio/sentence_breakdowns_igbo/i-do-not-understand.wav"),
  "i-am-hungry": require("../../assets/audio/sentence_breakdowns_igbo/i-am-hungry.wav"),
  "i-have-two-brothers": require("../../assets/audio/sentence_breakdowns_igbo/i-have-two-brothers.wav"),
  "i-will-come-tomorrow": require("../../assets/audio/sentence_breakdowns_igbo/i-will-come-tomorrow.wav"),
  "where-is-our-sister": require("../../assets/audio/sentence_breakdowns_igbo/where-is-our-sister.wav"),
  "they-are-tired": require("../../assets/audio/sentence_breakdowns_igbo/they-are-tired.wav"),
  "we-are-thirsty": require("../../assets/audio/sentence_breakdowns_igbo/we-are-thirsty.wav"),
  
  // Getting Started lesson (11)
  "give-him-water": require("../../assets/audio/sentence_breakdowns_igbo/give-him-water.wav"),
  "he-is-going-to-the-river-to-fetch-water": require("../../assets/audio/sentence_breakdowns_igbo/he-is-going-to-the-river-to-fetch-water.wav"),
  "i-am-going-to-see-my-father-at-the-farm": require("../../assets/audio/sentence_breakdowns_igbo/i-am-going-to-see-my-father-at-the-farm.wav"),
  "if-it-rains-we-will-stay-at-home": require("../../assets/audio/sentence_breakdowns_igbo/if-it-rains-we-will-stay-at-home.wav"),
  "my-house-is-bigger-than-your-house": require("../../assets/audio/sentence_breakdowns_igbo/my-house-is-bigger-than-your-house.wav"),
  "shall-we-go-see-them": require("../../assets/audio/sentence_breakdowns_igbo/shall-we-go-see-them.wav"),
  "the-boy-who-is-playing-football-is-my-friend": require("../../assets/audio/sentence_breakdowns_igbo/the-boy-who-is-playing-football-is-my-friend.wav"),
  "they-are-playing-football-near-the-school": require("../../assets/audio/sentence_breakdowns_igbo/they-are-playing-football-near-the-school.wav"),
  "they-walked-a-long-distance-this-morning": require("../../assets/audio/sentence_breakdowns_igbo/they-walked-a-long-distance-this-morning.wav"),
  "we-can-go-tomorrow": require("../../assets/audio/sentence_breakdowns_igbo/we-can-go-tomorrow.wav"),
  "we-cannot-go-home": require("../../assets/audio/sentence_breakdowns_igbo/we-cannot-go-home.wav"),
};

export const SENTENCE_BREAKDOWNS_EXAMPLE_IGBO_AUDIO: Record<string, number> = {
  "what-is-your-name-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/what-is-your-name-example.wav"),
  "how-are-you-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/how-are-you-example.wav"),
  "i-want-to-go-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-want-to-go-home-example.wav"),
  "i-do-not-understand-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-do-not-understand-example.wav"),
  "i-am-hungry-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-hungry-example.wav"),
  "i-have-two-brothers-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-have-two-brothers-example.wav"),
  "i-will-come-tomorrow-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-will-come-tomorrow-example.wav"),
  "where-is-our-sister-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/where-is-our-sister-example.wav"),
  "they-are-tired-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/they-are-tired-example.wav"),
  "we-are-thirsty-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/we-are-thirsty-example.wav"),
  "give-him-water-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/give-him-water-example.wav"),
  "he-is-going-to-the-river-to-fetch-water-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/he-is-going-to-the-river-to-fetch-water-example.wav"),
  "i-am-going-to-see-my-father-at-the-farm-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/i-am-going-to-see-my-father-at-the-farm-example.wav"),
  "if-it-rains-we-will-stay-at-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/if-it-rains-we-will-stay-at-home-example.wav"),
  "my-house-is-bigger-than-your-house-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/my-house-is-bigger-than-your-house-example.wav"),
  "shall-we-go-see-them-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/shall-we-go-see-them-example.wav"),
  "the-boy-who-is-playing-football-is-my-friend-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/the-boy-who-is-playing-football-is-my-friend-example.wav"),
  "they-are-playing-football-near-the-school-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/they-are-playing-football-near-the-school-example.wav"),
  "they-walked-a-long-distance-this-morning-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/they-walked-a-long-distance-this-morning-example.wav"),
  "we-can-go-tomorrow-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/we-can-go-tomorrow-example.wav"),
  "we-cannot-go-home-example": require("../../assets/audio/sentence_breakdowns_examples_igbo/we-cannot-go-home-example.wav"),
};

